# Generated by Django 5.0.4 on 2024-06-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_post_user_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
    ]
