# Generated by Django 5.0.4 on 2024-06-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_post_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AddField(
            model_name='post',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', upload_to='media/profile_pics/'),
        ),
    ]
